### ISSUE TITLE
Android/mobile support

### ISSUE THREAD

**Issue by lukasberbuer** [WICG/serial#103]
> Web apps should be able to do anything native apps can. We want to make it possible for you to build and deliver apps on the open web that have never been possible before.
-- https://web.dev/fugu-status/

Is there a reason why the Web Serial API is currently not supported on Android/mobile?

**Background**:
We currently experiment with the Web Serial API to control ultrasonic measurement devices and are very pleased with the results! Those ultrasonic devices can be connected to a desktop PC or to a tablet or smartphone with USB OTG. A full support of the serial API on mobile/desktop would allow us to just deploy a single PWA to our customers and stop the development of native apps.

Using the polyfill on top of Web USB for Android (https://github.com/google/web-serial-polyfill) doesn't work with our device/driver.

**Comment by reillyeon** [comment]
> Is there a reason why the Web Serial API is currently not supported on Android/mobile?

The Web Serial API is not supported on Android because that platform does not provide a Serial API for native applications. Apps which support USB serial adapters use the USB host API. The equivalent on the web is WebUSB and the web-serial-polyfill project is intended to support building apps this way on the web. If your device is unsupported by the polyfill patches are welcome to expand it.
