### ISSUE TITLE
TransformStream on port.readable: TypeError: readable is not of type ReadableStream

### ISSUE THREAD

**Issue by drinkbuddy** [WICG/serial#121]
I'm trying to program a **react-pwa** that uses the **serial api**.
To use streams i add _'@stardazed/streams'_ and _'@stardazed/streams-text-encoding'_ via yarn.
but i get this error:
_Uncaught (in promise) TypeError: Failed to execute 'pipeThrough' on 'ReadableStream': member readable is not of type ReadableStream._
***
Code (simplyfied):
```
class MyTransformer {
  constructor() {
    this.chunks = '';
  }

  start() {
    this.chunks = '';
  }

  transform(chunk, controller) {
    this.chunks += chunk;
    const lines = this.chunks.split("\r\n");
    this.chunks = lines.pop();
    lines.forEach((line) => controller.enqueue(line));
  }

  flush(controller) {
    controller.enqueue(this.chunks);
  }
}

async function onClick() {
    port = await navigator.serial.requestPort();
    await port.open({ baudRate: 115200 });

    const decoder = new TextDecoderStream();
    const stream = port.readable;

    const inputDone = stream.pipeTo(decoder.writable);
    const inputStream = decoder.readable.pipeThrough(new TransformStream(new MyTransformer()));

    let reader = inputStream.getReader();
    writer = port.writable.getWriter();

    readLoop(reader);
  }
```

**Comment by reillyeon** [comment]
This type of question is more appropriate for StackOverflow or the Chromium issue tracker. On the surface this code looks correct. I am suspicious that you had to include the @stardazed/streams and @stardazed/streams-text-encoding packages since if you are using the Serial API then you are targeting Chromium-based browsers which already have full support for WHATWG Streams and the TextEncoder/TextDecoder APIs.

@domenic or @ricea, is this an issue you've seen before with pipeThrough()?

**Comment by ricea** [comment]
Since the conversion to WebIDL last year, `pipeThrough()` checks that the `readable` passed into it is a platform `ReadableStream`. This means that using it with a polyfill will not work.

My guess of what is happening above is that you are getting the platform `TextDecoderStream`, but a polyfill of `TransformStream`, so they are not working together.

As @reillyeon said, all browsers that support the Serial API also support `TextDecoderStream` and `TransformStream`, so you don't need the polyfill.

**Comment by drinkbuddy** [comment]
how do i access the browser streams via node?

**Comment by ricea** [comment]
> how do i access the browser streams via node?

You'd probably have more success asking on Stackoverflow. The implementation for node seems to be stuck: https://github.com/nodejs/whatwg-stream.

**Comment by reillyeon** [comment]
> how do i access the browser streams via node?

If you're using the Web Serial API then you are in a browser, not Node, so I don't understand the relevance of the question.

**Comment by reillyeon** [comment]
Closing this issue. Please re-open if you are still having trouble after switching to using the browser's implementation of streams.
