### ISSUE TITLE
Browser adaptation

### ISSUE THREAD

**Issue by stylesuxx** [WICG/serial#129]
> I am not sure where else to ask/discuss this, so I try it here. Feel free to point me to the right place and close it here.

I have developed my first PWA using the Web Serial API. Right now I am telling users: use an up to date version of Chrome or Edge, but obviously they keep asking: What's with mobile? What's with $BROWSER_X?

So I was wondering, are there any plans of the Web Serial API to be implemented on Chrome for Android for example? I was not able to find anything to that regard - probably I am looking in the wrong place.

Also Mozilla and Safari sent strong signals against implementing this feature - I was wondering if enough user pressure might persuade them into implementing it anyway - are there any cases in which those vendors took a strong stance against something and then still went ahead implementing it?

**Comment by reillyeon** [comment]
> So I was wondering, are there any plans of the Web Serial API to be implemented on Chrome for Android for example? I was not able to find anything to that regard - probably I am looking in the wrong place.

Right now this API is not available in Chrome on Android because on other platforms it is based on the serial API provided by the operating system. The Android SDK doesn't include a serial API. What it does provide are USB and Bluetooth APIs. My team has developed [a polyfill library](https://github.com/google/web-serial-polyfill) which uses WebUSB to support standard USB CDC-ACM devices and there are open issues to expand this to more USB devices and support some common interfaces such as the Nordic UART through Web Bluetooth. Contributions there are welcome.

The remaining common "serial port" type not currently handled on Android using lower-level APIs is connecting to Bluetooth Classic RFCOMM endpoints. We are currently [prototyping support](https://bugs.chromium.org/p/chromium/issues/detail?id=1043300) for that using this API on desktop and that could be ported to Android, at which point the API would start to be available.

**Comment by stylesuxx** [comment]
That is very interesting insight - thank you. WebUSB actually seems to fit my use-case perfectly.
Your polyfill looks like it was made for my use-case, I will give it a spin right now.
