### ISSUE TITLE
'navigator.serial' is undefined in Chrome v91.0.4472.114 (Official Build) (ARM)

### ISSUE THREAD

**Issue by sreeram-solinst** [WICG/serial#142]
I am unable to access Web Serial API in Chrome in a MacBook Air with M1 processor.

**Expected Outcome:** 'navigator.serial' should be accessible in Chrome browser.

**Actual Outcome:** 'navigator.serial' is undefined and hence I am unable to access Web Serial API.

**Chrome browser version:** Version 91.0.4472.114 (Official Build) (ARM)

**Hardware device:** MacBook Air with M1 processor (ARM)

**Comment by reillyeon** [comment]
This is a Chromium issue, not a specification issue. Please file a report on crbug.com with a link to an example site demonstrating the issue you are encountering. The most common reason why `navigator.serial` will be undefined is because this API is only exposed in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), which means the page was served with HTTPS or from `localhost`.

To test whether the API is exposed properly on your system try clicking the "Serial" button on https://permission.site. It should show the device permission prompt.
