### ISSUE TITLE
A empty data package sent when web serial write data

### ISSUE THREAD

**Issue by qcscofield** [WICG/serial#168]
For example:
```
let chunk_size = 1024 * 1024
await device.open({baudRate: 115200, bufferSize: 1024 * 1024});
buffer = new Uint8Array(1024 * 1024 * 10)
let remainingBytes = buffer.byteLength
let i = 0
while (remainingBytes > 0) {
            let chunk = buffer.subarray(i * chunk_size, (i + 1) * chunk_size);
            let serialWriter = await device.writable.getWriter()
            serialWriter.write(chunk)
            await serialWriter.close()
            remainingBytes -= chunk.byteLength;
            i += 1;
}

```
10MB data loop 10 times to write. 
When writing 1MB of data, there is one empty packet for every 1KB sent.
Do you know why ?
![image](https://user-images.githubusercontent.com/31910172/179509219-a4cba9ff-d8fb-4be7-9950-b23dd604d7d4.png)

**Comment by demonguy** [comment]
The empty packet cause exception from the device
When device receive this empty packet, it will treat it as an invalid packet, and then return error.

**Comment by devanlai** [comment]
I'm pretty sure this is not specific to Web Serial.

IIRC, for USB CDC-ACM interfaces, zero-length packets are normal signaling mechanism and your application should be able to tolerate receiving them. And if your device is sending data, you may need to make sure that you send ZLPs as needed to avoid the case where it gets "stuck" when sending a multiple of the endpoint packet size.

It's been a while since I've reread the USB spec, so I'll leave it to other [StackOverflow answers](https://electronics.stackexchange.com/questions/253669/usb-cdc-help-with-zero-packets) and [online resources](https://docs.microsoft.com/en-us/azure/rtos/usbx/usbx-device-stack-5#general-considerations-for-bulk-transfer) to go over the details.

**Comment by reillyeon** [comment]
That is correct. A ZLP is sent at the end of a transaction which has just sent a full packet. This is performed by the USB CDC-ACM driver and it out of the control of applications using the platform serial API, such as implementations of the Web Serial API.

**Comment by demonguy** [comment]
Well. I'm not expert on USB CDC-ACM.
What i know is that Qualcomm's own flash tool and a native windows application developed by us can communicate with the serial port correct without such error. If it's USB CDC driver's problem. I cannot explain why other native windows application works well

**Comment by reillyeon** [comment]
Is the native Windows application writing chunks that are an exact multiple of the USB packet size (looks like 1024 bytes)?

**Comment by demonguy** [comment]
Well, after searching some document. I found Qualcomm firehose protocol have a configure option called "ZlpAwareHost=0".
In Windows it should be 1.
Which means, the device should handle the difference between Windows and Linux

Thanks very much. I found this solution because you mentioned "ZLP". So i just search it :)
