### ISSUE TITLE
error on reading serial webserial.io

### ISSUE THREAD

**Issue by davdavcoco** [WICG/serial#174]
anyone know about this? i get this loop error and stuck on reading..

my usb to rs232 is prolofic 
my device is digi di-30n its an digital scale with rs232

![IMG-20221103-WA0014](https://user-images.githubusercontent.com/24096349/199938947-56a77d90-483b-4e74-831c-f479204cf0cf.jpg)

**Comment by reillyeon** [comment]
From the errors I would guess that the baud rate is incorrect for communicating with the device and so the Prolific chip is interpreting the garbage it is receiving as parity and framing errors.

Closing this issue is off-topic. Please use Stackoverflow for asking questions about communicating with serial devices in general or the Chromium issue tracker if you think that a communication issue is due to an implementation bug. This repo is for discussion of the API specification.
