### ISSUE TITLE
Connection dissapeared when computer shutdown

### ISSUE THREAD

**Issue by TraFost** [WICG/serial#207]
does browser automatically forget the connection after we shutdown the  computer? and is there a way to implement auto connect to the serial port?

**Comment by reillyeon** [comment]
This isn't really a specification issue because exactly how permissions are managed is usually implementation-defined.

In Chromium, permissions to access a serial port are not always persistent. On Windows they are. On other platforms it requires the USB device to have a serial number. We've been tracking a feature request to improve this, but changes here have a security impact because they are only a heuristic.

To guarantee the ability to automatically connect to a serial port, you can use an enterprise policy such as [SerialAllowUsbDevicesForUrls](https://chromeenterprise.google/policies/#SerialAllowUsbDevicesForUrls) or [SerialAllowAllPortsForUrls](https://chromeenterprise.google/policies/#SerialAllowAllPortsForUrls) to control permissions instead of relying on the user-driven permission UI.
