### ISSUE TITLE
Supporting 'informed user choice' in port selection

### ISSUE THREAD

**Issue by JayBeavers** [WICG/serial#29]
I wanted to call out an idea @marcoscaceres posted in a separate thread:

![screenshot 2013-11-12 20 36 51](https://f.cloud.github.com/assets/870154/1525766/379e25ea-4bda-11e3-88a7-768456fd08b1.png)

I love this prototype and how it empowers the user to make an informed device choice.  In a separate discussion, we're working out the details about exposing port properties that can be used to infer device capabilities on the other end of the port.  Assuming we work this through and reach the ability to say, 'this port connects to a Sphero robot' or 'this port connects to an Arduino microcontroller with the Firmata protocol', how can we enable the building of a UI like above via our API?

I think it's going to be more complicated than a requestPorts() call popping a generic listbox.  Do we want the webpage to be able to skin the choice box (e.g. if the Manufacturer is Orbotix and the Product contains Sphero, show an icon for a Sphero robot next to the port name)?  I understand there's security risk here of masquerading the choice, but the benefit of enabling informed choice outweighs the risk imho.

**Comment by reillyeon** [comment]
This was fixed by #105 with the specification of `requestPort()`, which behaves similarly to the proposal in the issue description) and `getPorts()`, which will return all ports that a site has previously been granted permission to access. User agents are free to define out-of-band mechanisms for granting a site permission to access ports such as administrator settings. Such ports would be automatically present in the list returned by `getPorts()`.
