### ISSUE TITLE
Chrome Canary has an implementation of navigator.serial

### ISSUE THREAD

**Issue by Docteh** [WICG/serial#67]
Has anyone given it a look? Looks like its fairly recent, Its currently behind a flag as mentioned in the linked issue
https://bugs.chromium.org/p/chromium/issues/detail?id=884928#c44

`chrome://flags/#enable-experimental-web-platform-features`

**Comment by galvesribeiro** [comment]
Ohhh! That is great! I wonder when it will come (even as experimental flag) to the main track.

**Comment by larsgk** [comment]
Maybe @reillyeon knows?

**Comment by reillyeon** [comment]
The Chrome release schedule is here: https://chromiumdash.appspot.com/schedule

The code landed in time for the Chrome 77 branch. You can download dev-channel now and try it out or wait for it to hit beta-channel in early August or stable-channel in early September.

The implementation is still in flux and so the interface is expected to change as features are added and polished. What is implemented is different from in some cases and goes beyond in others what is specified here. Now that I have gained some implementation experience I will be submitting pull requests to bring this specification into alignment with the prototype implementation.

If you find bugs in the implementation please file them against the Blink>Serial component on crbug.com. If you have feature requests for the interface itself please file them as issues here.

Closing this issue because, well, it is not an issue. Thank you for your interest in this work. I am very excited to see what developers build with this new capability.

**Comment by galvesribeiro** [comment]
Thanks @reillyeon 

Looking forward for it!

Btw, you can check some of the use cases people are posting on this issue: https://github.com/WICG/serial/issues/36

**Comment by Docteh** [comment]
Any suggestions on where to look for general discussion about this? I don't have any bugs to report, as I'm sure my javascript problems are my own.

**Comment by reillyeon** [comment]
I recommend posting JavaScript questions on Stack Overflow because they provide an indexed archive of issues people have encountered in the past and that helps others who come along later.
