### ISSUE TITLE
reader.read() freezes

### ISSUE THREAD

**Issue by wieringen** [WICG/serial#90]
Hey guys,

Recently, I have been experimenting with your API (chrome 83.0.4103.116). The API is easy to work with, and connecting the device to my MacBook Pro (15-inch, 2017, Mojave) is a breeze. However, I'm having some trouble reading (terminating) streams. I'm experimenting with a medical device, which has a USB interface and returns JSON.

```js
let reader;
let writer;
const encoder = new TextEncoder();
const decoder = new TextDecoder();

async function connect() {
  const port = await navigator.serial.requestPort();
  await port.open({ baudrate: 9600 });
  reader = port.readable.getReader();
  writer = port.writable.getWriter();
}

async function config() {
  await writer.write(encoder.encode("configuration get\n"));
  while (true) {
    console.log("Start reading chunk")
    const { value, done } = await reader.read();
    console.log(done)
    if (done) {
      break;
    }
    const data = decoder.decode(value);
    console.log(data);
  }
}

export default {
  connect,
  config,
};
```
The snippet above is what I use to communicate with my device. Writing seems to work fine. When reading, however, the loop doesn't break, because "done" is never true. The last chunk of data contains (at the end) a null terminator + 5 byte termination (\0\r\n\r\n>). After the last chunk of data - with termination - is received; the reader is called again and freezes. 

Any idea how I can fix this issue?

**Comment by reillyeon** [comment]
The `ReadableStream` is not expected to close unless there is an error as defined [here](https://reillyeon.github.io/serial/#serialportsourcepullalgorithm-port-controller). Your code needs to know when it has received the last expected byte from the device and to not call `read()` again.

In this [code lab](https://codelabs.developers.google.com/codelabs/web-serial/#6) there are a few examples of using `TransformStream` to implement this kind of logic to parse messages out of a stream of bytes. For example, breaking messages on newlines or parsing out JSON objects.

**Comment by radio-miskovice** [comment]
I have the same problem: the connected device is not the initiator who would terminate the stream, nor does the application know in advance that it needs to terminate (because it is the user decision, unpredictable in its nature).

Example: a keyer (serial device) is sending status update when an event occurs (change of speed, text buffer empty, etc.). 
In idle condition, the app would listen for status change (e.g. change of keying speed caused by manually turning speed control potentiometer) => `reader.read()` was invoked and waits for asynchronous data to receive. In this situation, the user decides to terminate the application. `serialPort.close()` fails because `serialPort.readable` stream is locked. Is it not possible to call `reader.releaseLock()`, because reader is busy in `reader.read()`.
At least so it behaves in my browser.
I will post another issue with a clearer proposal what to do.
> 
> The `ReadableStream` is not expected to close unless there is an error as defined [here](https://reillyeon.github.io/serial/#serialportsourcepullalgorithm-port-controller). Your code needs to know when it has received the last expected byte from the device and to not call `read()` again.
>

**Comment by reillyeon** [comment]
My apologies for the low quality of my original answer. While there are cases where it is possible to know that `read()` should not be called again a generic solution for canceling a pending read is necessary and I have documented one in [Example 7](https://wicg.github.io/serial/#example-7) of the specification. Please see #112 for more details.
