### ISSUE TITLE
baudrate should probably be baudRate?

### ISSUE THREAD

**Issue by domenic** [WICG/serial#93]
A quick googling seems to indicate that it's two words, not a single word.

**Comment by monteslu** [comment]
why not just `baud` ?
Wouldn't have to worry about whether to capitalize Rate

**Comment by domenic** [comment]
In the upcoming spec revision I see a lot more `wordssmashedtogether` in the options dictionary: https://reillyeon.github.io/serial/#serialoptions-dictionary

This makes me suspect that these names are coming from some other ecosystem where `wordssmashedtogether` is an important convention. If that's the case, then that should be noted... and even then, I think it might be better to normalize them to web-style `camelCase`, since it's not an open-ended set.

**Comment by reillyeon** [comment]
There was some discussion of this in #87. I think some cases are easy. Example,

```
dictionary SerialOptions {
  required unsigned long baudRate;
  octet dataBits = 8;
  octet stopBits = 1;
  ParityType parity = "none";
  unsigned long bufferSize = 255;
  boolean rtscts = false;
};
```

The last one is tricky. "rtscts" refers to a hardware flow control mode where the "ready to send" and "clear to send" signals are used. In the signals dictionaries these are currently abbreviated but could be expanded like this,

```
dictionary SerialInputSignals {
  required boolean dataCarrierDetect;
  required boolean clearToSend;
  required boolean ringIndicator;
  required boolean dataSetReady;
};

dictionary SerialOutputSignals {
  boolean dataTerminalReady;
  boolean readyToSend;
  boolean break;
};
```

These names are still somewhat jargony and some signals have multiple names that have been used historically so we just have to pick one. I've been using [Wikipedia](https://en.wikipedia.org/wiki/RS-232#Data_and_control_signals) as a reference.

Maybe instead of a boolean "rtscts" parameter this should be an enum with two values,

 ```
enum FlowControlType {
  "none",
  "hardware",
};

dictionary SerialOptions {
  // ...
  FlowControlType flowControl = "none";
};
```

This would enable a third "software" mode where the operating system is instructed to send the XON and XOFF (ASCII codes 0x11 and 0x13) characters in order to manage the amount of incoming buffered data using in-band signaling rather than the out-of-band signals used by the "hardware" mode. This is not currently implemented in the prototype.

**Comment by domenic** [comment]
I don't feel qualified enough, in the area of knowing what serial developers want, to give a firm recommendation. But I will say that your IDL above looks pretty nice from the perspective of someone not embedded in that arena, and in terms of symmetry with the rest of the web platform.

And the idea of moving flowControl to an enum, especially if in the future it might grow a third state, makes a lot of sense regardless---even if the enum values end up staying as "none"/"rtscts" instead of "none"/"hardware".
